Repository slaclab/l2MpsLN, pull requests merged in 2020-04, with the labels that each got.

#28 Convert the processing window PVs to ns
  l2MpsLNApp/Db/mpsLN.substitutions
Labels: enhancement

#29 Fix parameter types used with YCPSWASYN
  configure/RELEASE
  l2MpsLNApp/Db/Reg1BitRO.template
  l2MpsLNApp/Db/Reg1BitRW.template
  l2MpsLNApp/Db/Reg4BitsRW.template
  l2MpsLNApp/Db/mpsLN.substitutions
Labels: bug

#30 Fix LCLS1 BSA implementation
  configure/RELEASE
  iocBoot/sioc-b084-mp02/st.cmd
  l2MpsLNApp/Db/Makefile
  l2MpsLNApp/Db/mpsLN.substitutions
  l2MpsLNApp/src/Makefile
  l2MpsLNApp/src/l2mps_l1bsa.cpp
  l2MpsLNApp/src/l2mps_l1bsa.h
Labels: bug

#31 Fix processing window PVs conversion to time
  firmware/mpsLN.dict
  l2MpsLNApp/Db/mpsLN.substitutions
Labels: bug, enhancement

#32 Bring TPR BSA drivers into link_node.cmd
  iocBoot/common/link_node.cmd
Labels: bug

#33 Bug fix: Remove hard-coded name, and use a macro instead
  l2MpsLNApp/Db/mpsLN.substitutions
Labels: bug

#34 Analog Values Autosave
  iocBoot/common/ana_units.req
  iocBoot/common/link_node.cmd
  iocBoot/common/mps_link_node_change_units.py
  iocBoot/sioc-b084-mp02/st.cmd
Labels: enhancement

#35 Bug fix: remove hard-coded name, and use macro instead
  l2MpsLNApp/Db/mpsLN.substitutions
Labels: bug
